#include "base_data_types.idl"

module process
{
    module plan
    {
        // QoSLibrary: EdgeBaseLibrary
        // QoSProfile: ConfigProfile

        //@copy-c-declaration static const char DRILLING_LIMITS[] = "DrillingLimits";

        /**
         * \ingroup actual
         *
         * \brief set of process limits for a given section specified by depth.
         *
         * | Variable          | Description                            | Data Type           |
         * | ----------------- | ---------------------------------------| --------------------|
         * | id                | id of requestor                        | DataTypes::Uuid     |
         * | startDepth        | start depth for constraints.           | units::length::meter       |
         * | endDepth          | end depth for contraints               | units::length::meter       |
         * | ropMin            | miniumu process rate of penetration limit      | units::velocity::meters_per_second |
         * | ropMax            | maximun process rate of penetration limit      | units::velocity::meters_per_second |
         * | wobMin            | minimum process weight on bit limit            | units::force::newton |
         * | wobMax            | maximum process weight on bit limit            | units::force::newton |
         * | diffPMin          | minimum process differential pressure limit    | units::pressure::pascal  |
         * | diffpMaxMax       | maximum process differential pressure limit    | units::pressure::pascal  |
         * | torqueMin         | minimum process differential torque limit      | units::torque::newton_meter |
         * | torqueMax         | maximum process differential torque limit      | units::torque::newton_meter |
         * | rotateMin         | minimum process rate in rad/s          | units::angular_velocity::radians_per_second |
         * | rotateMax         | maximum process rate in rad/s          | units::angular_velocity::radians_per_second |
         */
        struct DrillingLimits
        {
            DataTypes::Uuid  id; //@key
            double           startDepth; // (units::length::meter)
            double           endDepth;   // (units::length::meter)
            double           ropMin;     // (units::velocity::meters_per_second)
            double           ropMax;     // (units::velocity::meters_per_second)
            double           wobMin;     // (units::force::newton)
            double           wobMax;     // (units::force::newton)
            double           diffPMin;   // (units::pressure::pascal)
            double           diffPMax;   // (units::pressure::pascal)
            double           torqueMin;  // (units::torque::newton_meter)
            double           torqueMax;  // (units::torque::newton_meter)
            double           rotateMin;  // (units::angular_velocity::radians_per_second)
            double           rotateMax;  // (units::angular_velocity::radians_per_second)
        };
    };
};


