#include "base_data_types.idl"

module process
{
    module plan
    {
        // QoSLibrary: EdgeBaseLibrary
        // QoSProfile: EdgeBaseProfile

        //@copy-c-declaration static const char OBJECTIVE_STATE[] = "ObjectiveState";
        /**
         * \ingroup Actual
         *
         * \brief current state of rotation system.
         *
         * | Variable      | Description                            | Data Type         | 
         * | ------------- | ---------------------------------------| ------------------| 
         * | id            | id of requestor                        | DataTypes::Uuid   | 
         * | parentId      | id of parent objective                 | DataTypes::Uuid   | 
         * | timestamp     | timestamp when the data was published  | DataTypes::Time   | 
         * | objective     | current objective                      | DataTypes::Objective |
         */

        struct ObjectiveState
        {
            DataTypes::Uuid      id; //@key
            DataTypes::Uuid      parentId; 
            DataTypes::Time      timestamp;
            DataTypes::Objective objective;
        };
    };
};
