#include "base_data_types.idl"

module process
{
    module plan
    {
        //@copy-c-declaration static const char OBJECTIVE_STATE[] = "ObjectiveState";

        struct ObjectiveState
        {
            DataTypes::Uuid      id; //@key
            DataTypes::Uuid      parentId; 
            DataTypes::Time      timestamp;
            DataTypes::Objective objective;
        };
    };
};
