#include "base_data_types.idl"
module nec
{
    module process
    {
        //@copy-c-declaration static const char DRILL_REQUEST[] = "DrillRequest";

        /**
         * \brief requested state change in the drilling system.
         *
         * \ingroup SafeDrillFunctions
         *
         * | Variable           | Description                                      | Data Type           | Unit  |
         * | ------------------ | -------------------------------------------------| --------------------| ------|
         * | id                 | id of requestor                                  | DataTypes::Uuid     | N/A   |
         * | objectiveId        | id of current objective                          | DataTypes::Uuid     | N/A   |
         * | priority           | priority of the request                          | DataTypes::Priority | ms    |
         * | timeNeeded         | time requester needs the resource                | DataTypes::Time     | ms    |
         * | ropTarget          | target rate of penetration                       | double              | m/sec |
         * | wobTarget          | target weight on bit                             | double              | N     |
         * | diffPressureTarget | target differential pressure                     | double              | pas   |
         * | torqueTarget       | target differential torque                       | double              | Nm    |
         * | ropMode            | rate of penetration axis enabled                 | boolean             | N/A   |
         * | wobMode            | weight on bit axis enabled                       | boolean             | N/A   |
         * | diffPressureMode   | differential pressure axis enabled               | boolean             | N/A   |
         * | torqueMode         | differential torque mode enabled                 | boolean             | N/A   |
         */
        struct DrillRequest
        {
            DataTypes::Uuid     id; //@key
            DataTypes::Uuid     objectiveId;
            DataTypes::Priority priority;
            DataTypes::Time     timeNeeded;
            DataTypes::Time     duration;
            double              ropTarget;
            double              wobTarget;
            double              diffPressureTarget;
            double              torqueTarget;
            boolean             ropMode;
            boolean             wobMode;
            boolean             diffPressureMode;
            boolean             torqueMode;
        };

        //@copy-c-declaration static const char DRILL_OBJECTIVE[] = "DrillObjective";

        /**
         * \brief current requested state change in the drilling system.
         *
         * \ingroup SafeDrillFunctions
         *
         * | Variable           | Description                                      | Data Type       | Unit  |
         * | ------------------ | ------------------------------------------------ | ----------------| ------|
         * | id                 | id of requestor                                  | DataTypes::Uuid | N/A   |
         * | objectiveId        | id of current objective                          | DataTypes::Uuid | N/A   |
         * | estimatedDuration  | estimated duration requestor needs the resource  | DataTypes::Time | N/A   |
         * | ropTarget          | target rate of penetration                       | double              | m/sec |
         * | wobTarget          | target weight on bit                             | double              | N     |
         * | diffPressureTarget | target differential pressure                     | double              | pas   |
         * | torqueTarget       | target differential torque                       | double              | Nm    |
         * | ropMode            | rate of penetration axis enabled                 | boolean             | N/A   |
         * | wobMode            | weight on bit axis enabled                       | boolean             | N/A   |
         * | diffPressureMode   | differential pressure axis enabled               | boolean             | N/A   |
         * | torqueMode         | differential torque mode enabled                 | boolean             | N/A   |
         */
        struct DrillObjective
        {
            DataTypes::Uuid     id; //@key
            DataTypes::Uuid     objectiveId;
            DataTypes::Time     estimatedDuration;
            double              ropTarget;
            double              wobTarget;
            double              diffPressureTarget;
            double              torqueTarget;
            boolean             ropMode;
            boolean             wobMode;
            boolean             diffPressureMode;
            boolean             torqueMode;
        };

        //@copy-c-declaration static const char DRILL_STATE[] = "DrillState";

        /**
         * \brief current state of the drilling system.
         *
         * \ingroup SafeDrillFunctions
         *
         * | Variable           | Description                            | Data Type         | Unit  |
         * | ------------------ | -------------------------------------- | ----------------- | ------|
         * | id                 | id of requestor                        | DataTypes::Uuid   | N/A   |
         * | objectiveId        | id of current objective                | DataTypes::Uuid   | N/A   |
         * | timestamp          | timestamp when the data was published. | DataTypes::Time   | sec   |
         * | status             | status of ciruclation system           | Datatypes::Status | N/A   |
         * | ropActual          | actual rate of penetration             | double            | m/sec |
         * | wobActual          | actual weight on bit                   | double            | N     |
         * | diffPressureActual | actual differential pressure           | double            | pas   |
         * | torqueActual       | actual differential torque             | double            | Nm    |
         * | ropLimit           | machine rate of penetration limit      | double            | m/sec |
         * | wobLimit           | machine weight on bit limit            | double            | N     |
         * | diffPressureLimit  | machine differential pressure limit    | double            | pas   |
         * | torqueLimit        | machine differential torque limit      | double            | Nm    |
         * | ropMode            | rate of penetration axis enabled       | boolean           | N/A   |
         * | wobMode            | weight on bit axis enabled             | boolean           | N/A   |
         * | diffPressureMode   | differential pressure axis enabled     | boolean           | N/A   |
         * | torqueMode         | differential torque mode enabled       | boolean           | N/A   |
         * | ropTarget          | target rate of penetration             | double            | m/sec |
         * | wobTarget          | target weight on bit                   | double            | N     |
         * | diffPressureTarget | target differential pressure           | double            | pas   |
         * | torqueTarget       | target differential torque             | double            | Nm    |
         * | bitOnBottom        | bit on bottom                          | boolean           | N/A   |
         */
        struct DrillState
        {
            DataTypes::Uuid id; //@key
            DataTypes::Uuid objectiveId;
            DataTypes::Time timestamp;
            double          ropActual;
            double          wobActual;
            double          diffPressureActual;
            double          torqueActual;
            double          ropLimit;
            double          wobLimit;
            double          diffPressureLimit;
            double          torqueLimit;
            boolean         ropMode;
            boolean         wobMode;
            boolean         diffPressureMode;
            boolean         torqueMode;
            double          ropTarget;
            double          wobTarget;
            double          diffPressureTarget;
            double          torqueTarget;
            boolean         bitOnBottom;
        };
    };
};
