#include "base_data_types.idl"

module nec
{
    module process
    {
        //@copy-c-declaration static const char HOIST_REQUEST[] = "HoistRequest";

        /**
         * \brief requested state change in the hoisting system.
         *
         * \ingroup SafeHoistFunctions
         *
         * | Variable          | Description                                      | Data Type           | Unit  |
         * | ----------------- | -------------------------------------------------| --------------------| ------|
         * | id                | id of requestor                                  | DataTypes::Uuid     | N/A   |
         * | objectiveId       | id of current objective                          | DataTypes::Uuid     | N/A   |
         * | priority          | priority of the request                          | DataTypes::Priority | ms    |
         * | timeNeeded        | time requester needs the resource                | DataTypes::Time     | ms    |
         * | estimatedDuration | estimated duration requestor needs the resource  | DataTypes::Time     | N/A   |
         * | targetVelocity    | requested target in m/s                          | double              | m/sec |
         * | targetPosition    | requested target position in m                   | double              | m/sec |
         */
        struct HoistRequest
        {
            DataTypes::Uuid     id;           //@key
            DataTypes::Uuid     objectiveId; 
            DataTypes::Priority priority;
            DataTypes::Time     timeNeeded;
            DataTypes::Time     estimatedDuration;
            double              targetVelocity;
            double              targetPosition;
        };

        //@copy-c-declaration static const char HOIST_OBJECTIVE[] = "HoistObjective";

        /**
         * \brief current requested state change in the hoisting system.
         *
         * \ingroup SafeHoistFunctions
         *
         * | Variable          | Description                                      | Data Type       | Unit  |
         * | ----------------- | ------------------------------------------------ | ----------------| ------|
         * | id                | id of requestor                                  | DataTypes::Uuid | N/A   |
         * | objectiveId       | id of current objective                          | DataTypes::Uuid | N/A   |
         * | estimatedDuration | estimated duration requestor needs the resource  | DataTypes::Time | N/A   |
         * | targetVelocity    | requested target in m/s                          | double          | m/sec |
         * | targetPosition    | requested target position in m                   | double          | m/sec |
         */
        struct HoistObjective
        {
            DataTypes::Uuid  id; //@key
            DataTypes::Uuid  objectiveId; 
            DataTypes::Time  estimatedDuration;
            double           targetVelocity;
            double           targetPosition;
        };

        //@copy-c-declaration static const char HOIST_STATE[] = "HoistState";

        /**
         * \brief current state of the hoisting system.
         *
         * \ingroup SafeHoistFunctions
         *
         * | Variable          | Description                            | Data Type         | Unit  |
         * | ----------------- | -------------------------------------- | ----------------- | ------|
         * | id                | id of requestor                        | DataTypes::Uuid   | N/A   |
         * | objectiveId       | id of current objective                | DataTypes::Uuid   | N/A   |
         * | timestamp         | timestamp when the data was published. | DataTypes::Time   | sec   |
         * | status            | status of ciruclation system           | Datatypes::Status | N/A   |
         * | actualVelocity    | actual velicoty in m/s                 | double            | m/sec |
         * | actualPosition    | requested target in m                  | double            | m/sec |
         * | maxHoistVelocity  | requested target in m/s                | double            | m/sec |
         * | maxLowerVelocity  | requested target in m/s                | double            | m/sec |
         * | maxHoistPosition  | requested target in m/s                | double            | m/sec |
         * | maxLowerPosition  | requested target in m/s                | double            | m/sec |
         * | targetVelocity    | requested target in m/s                | double            | m/sec |
         * | targetPosition    | requested target position in m         | double            | m/sec |
         */
        struct HoistState
        {
            DataTypes::Uuid     id;   //@key
            DataTypes::Uuid     objectiveId; 
            DataTypes::Time     timestamp;
            DataTypes::Status   status;

            // actuals
            double              actualHookload;
            double              actualVelocity;
            double              actualPosition;

            // constraints
            double              maxHookload;
            double              maxHoistVelocity;
            double              maxLowerVelocity;
            double              maxHoistPosition;
            double              maxLowerPosition;

            // targets
            double              targetVelocity;
            double              targetPosition;
        };
    };
};
