#include "base_data_types.idl"

module nec
{
    module process
    {
        // QoSLibrary: EdgeBaseLibrary
        // QoSProfile: EdgeBaseProfile

        //@copy-c-declaration static const char ROTATE_REQUEST[] = "RotateRequest";
        /**
         * \ingroup Request
         *
         * \brief Requested state change in the rotation system.
         *
         * Long Description Goes Here 1
         * Long Description Goes Here 2
         * Long Description Goes Here 3
         * Long Description Goes Here 4
         *
         * | Variable          | Description                                         | Data Type           | 
         * | ----------------- | --------------------------------------------------- | ------------------- | 
         * | id                | id of requestor                                     | DataTypes::Uuid     | 
         * | objectiveId       | id of current objective                             | DataTypes::Uuid     | 
         * | priority          | priority of the request                             | DataTypes::Priority | 
         * | timeNeeded        | time requester needs the resource                   | DataTypes::Time     | 
         * | estimatedDuration | estimated duration requestor needs the resource     | DataTypes::Time     | 
         * | targetRate        | requested traget in rad/s                           | units::angular_velocity::radians_per_second  |
         */
        struct RotateRequest
        {
            DataTypes::Uuid     id;          //@key
            DataTypes::Uuid     objectiveId; 
            DataTypes::Priority priority;
            DataTypes::Time     timeNeeded;
            DataTypes::Time     estimatedDuration;
            double              targetRate;  
        };

        // QoSLibrary: EdgeBaseLibrary
        // QoSProfile: EdgeBaseProfile

        //@copy-c-declaration static const char ROTATE_OBJECTIVE[] = "RotateObjective";
        /**
         * \ingroup Objective
         *
         * \brief Current requested state change in the rotation system.
         *
         * | Variable          | Description                                        | Data Type        |
         * | ----------------- | -------------------------------------------------- | ---------------- |
         * | id                | id of requestor                                    | DataTypes::Uuid  |
         * | objectiveId       | id of current objective                            | DataTypes::Uuid  |
         * | estimatedDuration | estimated duration requestor needs the resource    | DataTypes::Time  |
         * | targetRate        | requested traget in rad/s                          | units::angular_velocity::radians_per_second |
         */
        struct RotateObjective
        {
            DataTypes::Uuid  id;                //@key
            DataTypes::Uuid  objectiveId; 
            DataTypes::Time  estimatedDuration; 
            double           targetRate;        
        };

        // QoSLibrary: EdgeBaseLibrary
        // QoSProfile: EdgeBaseProfile

        //@copy-c-declaration static const char ROTATE_STATE[] = "RotateState";
        /**
         * \ingroup Actual
         *
         * \brief Current state of rotation system.
         *
         * | Variable      | Description                            | Data Type         | 
         * | ------------- | ---------------------------------------| ------------------| 
         * | id            | id of requestor                        | DataTypes::Uuid   | 
         * | objectiveId   | id of current objective                | DataTypes::Uuid   | 
         * | timestamp     | timestamp when the data was published  | DataTypes::Time   | 
         * | status        | Unique id of publisher                 | Datatypes::Status | 
         * | actualRate    | actual rate in rad/s                   | units::angular_velocity::radians_per_second |
         * | minRate       | minimum machine rate in rad/s          | units::angular_velocity::radians_per_second |
         * | maxRate       | maximum machine rate in rad/s          | units::angular_velocity::radians_per_second |
         * | targetRate    | requested traget in rad/s              | units::angular_velocity::radians_per_second |
         */
        struct RotateState
        {
            DataTypes::Uuid   id;           //@key
            DataTypes::Uuid   objectiveId; 
            DataTypes::Time   timestamp;        
            DataTypes::Status status;
            double            actualRate;  
            double            minRate;  
            double            maxRate;  
            double            targetRate;  
        };
    };
};
