#include "base_data_types.idl"

module nec
{
    module process
    {
        // QoSLibrary: EdgeBaseLibrary
        // QoSProfile: EdgeBaseProfile

        //@copy-c-declaration static const char WELLBORE_STATE[] = "WellboreState";

        /**
         *
         * \ingroup Actual
         *
         * \brief Wellbore state information.
         *
         * | Variable         | Description                                            | Data Type  |
         * | ---------------- | ------------------------------------------------------ | -----------|
         * | id               | Unique id of publisher.                                | DataTypes::Uuid   |
         * | timestamp        | Timestamp when the data was published.                 | DataTypes::Time   | 
         * | holeDepth        | Reported hole depth.                                   | units::length::meter       |
         * | measuredDepth    | Measured depth of hole.                                | units::length::meter       |
         * | trueVerticalDepth| Measured true vertical depth of hole.                  | units::length::meter       |
         * | bitDepth         | Measured depth of bit.                                 | units::length::meter       |
         */
        struct WellboreState
        {
            DataTypes::Uuid  id; //@key
            DataTypes::Uuid  objectiveId; 
            DataTypes::Time  timestamp;
            double           holeDepth;
            double           measuredDepth;
            double           trueVerticalDepth;
            double           bitDepth;
        };
    };
};
