module Shell
{
    module Hmi
    {
        module AutoTunerConfiguration
        {
            // QoSLibrary: EdgeBaseLibrary
            // QoSProfile: ConfigProfile

            //@copy-c-declaration static const char MODEL_STATE_STATE[] = "ModelState";
            /**
             * \brief Requested state change in the rotation system.
             *
             * | Variable          | Description                                         | Data Type           | 
             * | ----------------- | --------------------------------------------------- | ------------------- | 
             * | pipeInnerDiameter | id of requestor                                     | units::length::meter| 
             * | pipeOuterDiameter | id of current objective                             | units::length::meter| 
             */
            struct ModelState
            {
                double  pipeInnerDiameter;
                double  pipeOuterDiameter;
                double  slopeFilter;
                double  tauMax;
                double  tauMin;
                double  tauMultiplier;
                double  maxDeviation;
                double  minInterval;
                boolean tunerEnabled;
            };

            //@copy-c-declaration static const char DIFFP_TUNING_STATE[] = "DiffpTuningState";
            struct DiffpTuningState
            {
                double  filter;
                double  d;
                double  f;
                double  epsilon;
                boolean epsilonManual;
                double  kcMin;
                double  kcMax;
                double  tiMin;
                double  tiMax;
                double  initK;
                double  initTau;
                double  initPreFilter;
                double  r1;
                double  r2;
            };
    
            //@copy-c-declaration static const char WOB_TUNING_STATE[] = "WobTuningState";
            struct WobTuningState
            {
                double  filter;
                double  d;
                double  f;
                double  epsilon;
                boolean epsilonManual;
                double  kcMin;
                double  kcMax;
                double  tiMin;
                double  tiMax;
                double  initK;
                double  initTau;
                double  initPreFilter;
                double  r1;
                double  r2;
            };
    
            //@copy-c-declaration static const char TORQUE_TUNING_STATE[] = "TorqueTuningState";
            struct TorqueTuningState
            {
                double  filter;
                double  d;
                double  f;
                double  epsilon;
                boolean epsilonManual;
                double  kcMin;
                double  kcMax;
                double  tiMin;
                double  tiMax;
                double  initK;
                double  initTau;
                double  initPreFilter;
                double  r1;
                double  r2;
            };
        };
    };
};
