module Shell
{
    module Hmi
    {
        module RoptimizerConfiguration
        {
            //@copy-c-declaration static const char MODEL_STATE_REQUEST[] = "ModelStateRequest";
            struct RoptimizerCnfigurationRequest
            {
                double steadyStateWindow;
                double steadyStateMin;
                double rpmStepSize;
                double ropStepSize;
            };

            //@copy-c-declaration static const char MODEL_STATE_REQUEST[] = "ModelStateRequest";
            struct SteadyState
            {
                boolean rpm;
                boolean rop;
                boolean wob;
                boolean torque;
            };
        };
    };
};
