module Shell
{
    module Hmi
    {
        module RoptimizerConfiguration
        {
            //@copy-c-declaration static const char ROPTIMIZER_CONFIGURATION_REQUEST[] = "RoptimizerConfigurationRequest";
            struct RoptimizerConfigurationRequest
            {
                long steadyStateWindow;
                long steadyStateMin;
                long rpmStepSize;
                long ropStepSize;
            };

            //@copy-c-declaration static const char ROPTIMIZER_STEADY_STATE[] = "RoptimizerSteadyState";
            struct RoptimizerSteadyState
            {
                // Actuals
                boolean rpmSteadyState;
                boolean ropSteadyState;
                boolean wobSteadyState;
                boolean torqueSteadyState;
                // Targets
                long steadyStateWindow;
                long steadyStateMin;
                long rpmStepSize;
                long ropStepSize;
                double bitWear;
                double mse;
                double power;
            };
        };
    };
};
