module Shell
{
    module Hmi
    {
        module RoptimizerConfiguration
        {
            //@copy-c-declaration static const char ROPTIMIZER_CONFIGURATION_REQUEST[] = "RoptimizerConfigurationRequest";
            struct RoptimizerConfigurationRequest
            {
                double steadyStateWindow;
                double steadyStateMin;
                double rpmStepSize;
                double ropStepSize;
            };

            //@copy-c-declaration static const char ROPTIMIZER_STEADY_STATE[] = "RoptimizerSteadyState";
            struct RoptimizerSteadyState
            {
                double rpmState;
                double ropState;
                double wobState;
                double torqueState;
            };
        };
    };
};
