#include "base_data_types.idl"

module nec
{
    module control
    {
        //@copy-c-declaration static const char HMI_REQUEST[] = "HmiRequest";
        struct HmiRequest
        {
            DataTypes::Uuid   id;           //@key
            DataTypes::Time   timestamp;
            long    mode;
            double  modeController;
            double  differentialPressureRequestK;
            double  differentialPressureRequestTau;
            double  rateOfPenetrationRequestK;
            double  rateOfPenetrationRequestTau;
            double  torqueRequestK;
            double  torqueRequestTau;
            double  weightOnBitRequestK;
            double  weightOnBitRequestTau;
            long    status;
            boolean tuningEnable;
        };

    };
};
