#include "base_data_types.idl"

module nec
{
    module control
    {
        //@copy-c-declaration static const char ROTATE_ENGINEERING_REQUEST[] = "RotateEngineeringRequest";

        struct RotateRequest
        {
            DataTypes::Uuid     id;          //@key
            DataTypes::Priority priority;    // priority of the request
            DataTypes::Time     timeNeeded;  // time requester needs the resource
            DataTypes::Time     duration;    // duration requester needs the resource
            double              targetRate;  // requested traget in rad/s
        };

        //@copy-c-declaration static const char ROTATE_ENGINEERING_OBJECTIVE[] = "RotateEngineeringObjective";

        struct RotateObjective
        {
            DataTypes::Uuid     id;                //@key
            DataTypes::Time     estimatedDuration; // estimated time current requestor owns the resource
            double              targetRate;  // requested traget in rad/s
            double              targetTorque;  // requested traget in rad/s
        };

        //@copy-c-declaration static const char ROTATE_ENGINEERING_STATE[] = "RotateEngineeringState";

        struct RotateState
        {
            DataTypes::Uuid     id;           //@key
            DataTypes::Status   status;
            DataTypes::Time     timestamp;        

            // acutals
            double  actualRate;
            double  actualTorque;

            // constraints
            double  minRate;
            double  maxRate;
            double  minTorque;
            double  maxTorque;

            // targets
            double  targetRate;
        };
    };
};
