#include "base_data_types.idl"

module ControlRotation
{
    //@copy-c-declaration static const char TORQUE_REQUEST[] = "TorqueState";

    struct TorqueRequest
    {
        DataTypes::Uuid     id;          //@key
        DataTypes::Priority priority;    // priority of the request
        DataTypes::Time     timeNeeded;  // time requester needs the resource
        DataTypes::Time     duration;    // duration requester needs the resource
        double              target;      // requested traget in rad/s
    };

    //@copy-c-declaration static const char TORQUE_OBJECTIVE[] = "TorqueState";

    struct TorqueObjective
    {
        DataTypes::Uuid     id;                //@key
        DataTypes::Time     estimatedDuration; // estimated time current requestor owns the resource
        double              limit;             // current traget in rad/s
    };

    //@copy-c-declaration static const char TORQUE_STATE[] = "TorqueState";

    struct TorqueState
    {
        DataTypes::Uuid     id;           //@key
        DataTypes::Status   status;

        // acutals
        double  actual;       // current rate of rotation expressed in rad/s

        // constraints
        double  minForce;     // minimum rate of rotation expressed in rad/s
        double  maxForce;     // maximum rate of rotation expressed in rad/s

        // targets
        double  limit;        // current traget in rad/s
    };
};
