module process
{
    module maintanence
    {
        //@copy-c-declaration static const char PROCESS_INFO[] = "ProcessInfo";

        struct ProcessState
        {
            char      processName[128]; //@key
            long      pid;
            long long upTime;
            long long totalVirtualMemory;
            long long usedVirtualMemory;
            long long totalPhysicalMemory;
            long long usedPhysicalMemory;
        };
    };
};
