#include "base_data_types.idl"

module process
{
    module maintanence
    {
        //@copy-c-declaration static const char PROCESS_INFO[] = "ProcessInfo";

        struct ProcessState
        {
            DataTypes::Time     timestamp;
            string              processName; //@key
            long                pid;
            double              upTime;
            double              cpuPercent;
            double              vmPeak;
            double              vmSize;
            double              vmSwap;
            double              vmMaxSwap;
            long                threads;
        };
    };
};
