module DataTypes
{
    /**
    * @brief Unique ID for all topics
    */
    typedef string<36> Uuid;
    
    /**
    * @brief time of day based on Unix Epoch
    */
    struct Time
    {
        long sec;               ///< The seconds.
        unsigned long nanosec;  ///< The nanoseconds.
    };

    /**
    * @brief sets the priority of the request
    */
    enum Priority  
    {
        Normal,   ///< Normal priority.
        High,     ///< High priority.
        Critical  ///< Critical priority.
    };

    enum SurveyQuality
    {
        Definitive,
        Inconclusive
    };

    enum Status
    {
        Fault,
        Good
    };

    enum PipeType
    {
        DrillCollar,
        HeavyWeight,
        DrillPipe
    };

    enum Objective
    {
        InitialState,
        None,
        Casing,
        CleaningHole,
        Drilling,
        Sliding,
        AutoReaming,
        Tripping
    };
};
