module DataTypes
{
    typedef string<36> Uuid;

    struct Time //@brief time of day based on Unix Epoch
    {
        long sec;               ///< The seconds.
        unsigned long nanosec;  ///< The nanoseconds.
    };

    enum Priority  //@brief sets the priority of the request
    {
        Normal,   ///< Normal priority.
        High,     ///< High priority.
        Critical  ///< Critical priority.
    };

    enum SurveyQuality
    {
        Definitive,
        Inconclusive
    };

    enum Status
    {
        Fault,
        Good
    };

    enum PipeType
    {
        DrillCollar,
        HeavyWeight,
        DrillPipe
    };

    enum Objective
    {
        None,
        Casing,
        CleaningHole,
        Drilling,
        Tripping
    };
};
