module Configuration
{
    enum config_type
    {
        PROTOCOL,
        INTERFACE,
        STEP7_INTERFACE
    };

    enum plant_type
    {
        BOOLEAN,
        INT8,
        UNSIGNEDINT8,
        INT16,
        UNSIGNEDINT16,
        INT32,
        UNSIGNEDINT32,
        INT64,
        UNSIGNEDINT64,
        FLOAT,
        DOUBLE
    };
    
    struct protocol_t
    {
        string protocol;
        string endpoint;
    };

    struct interface_t
    {
        string protocol;
        string type;
        string unit;
        string tag;
    };

    struct step7_interface_t
    {
        string protocol;
        string type;
        string unit;
        long   dataBlock;
        long   offset;
    };

    union config_data switch ( config_type )
    {
        case PROTOCOL:
            protocol_t  event;

        case INTERFACE:
            interface_t  request;

        case STEP7_INTERFACE:
            step7_interface_t  step7_data;
    };

    //@copy-c-declaration static const char CONFIGURATION_ITEM[] = "ConfigurationItem";
    struct Item
    {
        string       key; //@key
        config_type  configType;
        config_data  configData;
    };
};
