module Configuration
{
    enum config_type
    {
        PROTOCOL,
        INTERFACE,
        TAG
    };

    enum plant_type
    {
        BOOLEAN,
        INT8,
        UNSIGNEDINT8,
        INT16,
        UNSIGNEDINT16,
        INT32,
        UNSIGNEDINT32,
        INT64,
        UNSIGNEDINT64,
        FLOAT,
        DOUBLE
    };
    
    struct protocol_t
    {
        string protocolId;
        string protocol;
        string endpoint;
    };

    struct interface_t
    {
        string ddsInterface;
        string protocolId;
        string baseAddress;
        string elements;
    };

    struct tag_t
    {
        string edgeType;
        string type;
        string io_unit;
        string tag;
    };

    union config_data switch ( config_type )
    {
        case PROTOCOL:
            protocol_t   protocolSpec;

        case INTERFACE:
            interface_t  interfaceSpec;

        case TAG:
            tag_t        tagSpec;
    };

    //@copy-c-declaration static const char CONFIGURATION_ITEM[] = "ConfigurationItem";
    struct Item
    {
        string       key; //@key
        config_type  configType;
        config_data  configData;
    };
};
