###############################################################################
# liblogger Library Makefile
###############################################################################
#
# The following variables must be set for the makefile to work correctly
#
# TARG_BUILD_MAJOR   - Version number major
# TARG_BUILD_MINOR   - Version number minor
# TARG_BUILD_VERSION - Version number patch
# TARGET_TYPE        - library, staticlib, executable, unittest or thirdparty
# TARGET_NAME        - Name of final executable/library
# TARG_DESCRIPTION   - Brief description of the package for debian control file
#
###############################################################################
include ../Makefiles/Makefile.platform

TARG_SOURCE_DIR =
TARG_BUILD_MAJOR =
TARG_BUILD_MINOR =
TARG_BUILD_VERSION =
TARGET_TYPE =
TARGET_NAME =

###############################################################################
# compilation flags
###############################################################################
# Includes
TARG_INCLUDES +=

# Libraries
TARG_LIBS +=

# Sources
TARG_SOURCES +=

###############################################################################
# Installation section
###############################################################################

# package control file
PACKAGE_DESCRIPTION =
PACKAGE_EXTENDED_DESCRIPTION =
PACKAGE_MAINTAINER =
PACKAGE_DEPENDENCIES =
PACKAGE_DEV_DEPENDENCIES =

# package include files
PACKAGE_INCLUDE_FILES +=

# package configuration files
PACKAGE_CONFIGURATION_FILES +=

###############################################################################
# Makefiles included to configure the compiler, etc for the current platform
###############################################################################
include $(TOP_DIR)/Makefiles/Makefile.rti
include $(TOP_DIR)/Makefiles/Makefile.macros
include $(TOP_DIR)/Makefiles/Makefile.basic
