#include "base_data_types.idl"
module plc
{
    module process
    {
        //@copy-c-declaration static const char PLC_DRILL_REQUEST[] = "PlcDrillRequest";

        /**
         * \brief requested state change in the drilling system.
         *
         * \ingroup SafeDrillFunctions
         *
         * | Variable           | Description                                      | Data Type           | Unit  |
         * | ------------------ | -------------------------------------------------| --------------------| ------|
         * | ropLimit           | rate of penetration limit                        | double              | m/sec |
         * | wobLimit           | weight on bit limit                              | double              | N     |
         * | diffPressureLimit  | differential pressure limit                      | double              | pas   |
         * | torqueLimit        | differential torque limit                        | double              | Nm    |
         * | ropMode            | rate of penetration axis enabled                 | boolean             | N/A   |
         * | wobMode            | weight on bit axis enabled                       | boolean             | N/A   |
         * | diffPressureMode   | differential pressure axis enabled               | boolean             | N/A   |
         * | torqueMode         | differential torque mode enabled                 | boolean             | N/A   |
         */
        struct DrillRequest
        {
            double              ropLimit;
            double              wobLimit;
            double              diffPressureLimit;
            double              torqueLimit;
            boolean             ropMode;
            boolean             wobMode;
            boolean             diffPressureMode;
            boolean             torqueMode;
        };

        //@copy-c-declaration static const char PLC_DRILL_STATE[] = "PlcDrillState";

        /**
         * \brief current state of the drilling system.
         *
         * \ingroup SafeDrillFunctions
         *
         * | Variable                  | Description                            | Data Type         | Unit  |
         * | ------------------------- | -------------------------------------- | ----------------- | ------|
         * | ropActual                 | actual rate of penetration             | double            | m/sec |
         * | wobActual                 | actual weight on bit                   | double            | N     |
         * | diffPressureActual        | actual differential pressure           | double            | pas   |
         * | torqueActual              | actual differential torque             | double            | Nm    |
         * | ropMachineLimit           | machine rate of penetration limit      | double            | m/sec |
         * | wobMachineLimit           | machine weight on bit limit            | double            | N     |
         * | diffPressureMachineLimit  | machine differential pressure limit    | double            | pas   |
         * | torqueMachineLimit        | machine differential torque limit      | double            | Nm    |
         * | ropMode                   | rate of penetration axis enabled       | boolean           | N/A   |
         * | wobMode                   | weight on bit axis enabled             | boolean           | N/A   |
         * | diffPressureMode          | differential pressure axis enabled     | boolean           | N/A   |
         * | torqueMode                | differential torque mode enabled       | boolean           | N/A   |
         * | ropLimit                  | target rate of penetration             | double            | m/sec |
         * | wobLimit                  | target weight on bit                   | double            | N     |
         * | diffPressureLimit         | target differential pressure           | double            | pas   |
         * | torqueLimit               | target differential torque             | double            | Nm    |
         */
        struct DrillState
        {
            double          ropActual;
            double          wobActual;
            double          diffPressureActual;
            double          torqueActual;
            double          ropMachineLimit;
            double          wobMachineLimit;
            double          diffPressureMachineLimit;
            double          torqueMachineLimit;
            boolean         ropMode;
            boolean         wobMode;
            boolean         diffPressureMode;
            boolean         torqueMode;
            double          ropLimit;
            double          wobLimit;
            double          diffPressureLimit;
            double          torqueLimit;
        };
    };
};
