#include "base_data_types.idl"

module plc
{
    module process
    {
        //@copy-c-declaration static const char ROTATE_REQUEST_TOPIC[] = "RotateRequestTopic";

        /**
         * \brief requested state change in the rotation system.
         *
         * \ingroup SafeRotationFunctions
         *
         * | Variable          | Description                                         | Data Type           | Unit    |
         * | ----------------- | --------------------------------------------------- | ------------------- | ------- |
         * | targetRate        | requested traget in rad/s                           | double              | rad/s   |
         */
        struct PlcRotateRequest
        {
            double targetRate;
        };

        //@copy-c-declaration static const char ROTATE_STATE_TOPIC[] = "RotateStateTopic";

        /**
         * \brief current state of rotation system.
         *
         * \ingroup SafeRotationFunctions
         *
         * | Variable      | Description                            | Data Type         | Unit  |
         * | ------------- | ---------------------------------------| ------------------| ------|
         * | status        | Unique id of publisher                 | Datatypes::Status | N/A   |
         * | actualRate    | actual rate in rad/s                   | double            | rad/s |
         * | minRate       | minimum machine rate in rad/s          | double            | rad/s |
         * | maxRate       | maximum machine rate in rad/s          | double            | rad/s |
         * | targetRate    | requested traget in rad/s              | double            | rad/s |
         */
        struct PlcRotateState
        {
            long    status;

            // actuals
            double  actualRate;

            // constraints
            double  minRate;
            double  maxRate;

            // targets
            double  targetRate;
        };
    };
};
