module plc
{
    module process
    {
        // QoSLibrary: EdgeBaseLibrary
        // QoSProfile: PlcProfile
        //@copy-c-declaration static const char PLC_CIRCULATE_REQUEST_TOPIC[] = "CirculateRequestTopic";

        /**
         * \brief requested state change in the circulation system.
         *
         * \ingroup SafeCirculateFunctions
         *
         * | Variable                | Description                            | Data Type         | Unit    |
         * | ----------------------- | ---------------------------------------| ------------------| ------- |
         * | targetFlowRate          | requetsed flow rate                    | double            | m/sec^3 |
	 */
        struct PlcCirculateRequest
        {
            double targetFlowRate; ///< requested flow rate in m/sec^3
        };

        // QoSLibrary: EdgeBaseLibrary
        // QoSProfile: PlcProfile
        //@copy-c-declaration static const char PLC_CIRCULATE_STATE_TOPIC[] = "CirculateStateTopic";

        /**
         * \brief current state of circulation system.
         *
         * \ingroup SafeCirculateFunctions
         *
         * | Variable                | Description                            | Data Type         | Unit    |
         * | ----------------------- | ---------------------------------------| ------------------| ------- |
         * | status                  | status of ciruclation system           | Datatypes::Status | N/A     |
         * | actualFlowRate          | actual flow rate                       | double            | m/sec^3 |
         * | actualStandpipePressure | actual standpipe pressure              | double            | Pa      |
         * | minFlowRate             | minimum machine flow rate              | double            | m/sec^3 |
         * | maxFlowRate             | maximum machine flow rate              | double            | m/sec^3 |
         * | minStandpipePressure    | minimum machine standpipe pressure     | double            | Pa      |
         * | maxStandpipePressure    | maximum machine standpipe pressure     | double            | Pa      |
         * | targetFlowRate          | requetsed flow rate                    | double            | m/sec^3 |
         */
        struct PlcCirculateState
        {
            long    status;

            // actuals
            double  actualFlowRate;
            double  actualStandpipePressure;

            // constraints
            double  minFlowRate;
            double  maxFlowRate;
            double  minStandpipePressure;
            double  maxStandpipePressure;

            // targets
            double  targetFlowRate;
        };
    };
};
