#include "base_data_types.idl"

module plc
{
    module process
    {
        //@copy-c-declaration static const char CIRCULATE_REQUEST_TOPIC[] = "CirculateRequestTopic";

        /**
         * \brief requested state change in the circulation system.
         *
         * \ingroup SafeCirculateFunctions
         *
         * | Variable                | Description                            | Data Type         | Unit    |
         * | ----------------------- | ---------------------------------------| ------------------| ------- |
         * | targetFlowRate          | requetsed flow rate                    | double            | m/sec^3 |
	 */
        struct CirculateRequest
        {
            double targetFlowRate; ///< requested flow rate in m/sec^3
        };

        //@copy-c-declaration static const char CIRCULATE_STATE_TOPIC[] = "CirculateStateTopic";

        /**
         * \brief current state of circulation system.
         *
         * \ingroup SafeCirculateFunctions
         *
         * | Variable                | Description                            | Data Type         | Unit    |
         * | ----------------------- | ---------------------------------------| ------------------| ------- |
         * | status                  | status of ciruclation system           | Datatypes::Status | N/A     |
         * | actualFlowRate          | actual flow rate                       | double            | m/sec^3 |
         * | actualStandpipePressure | actual standpipe pressure              | double            | Pa      |
         * | minFlowRate             | minimum machine flow rate              | double            | m/sec^3 |
         * | maxFlowRate             | maximum machine flow rate              | double            | m/sec^3 |
         * | minStandpipePressure    | minimum machine standpipe pressure     | double            | Pa      |
         * | maxStandpipePressure    | maximum machine standpipe pressure     | double            | Pa      |
         * | targetFlowRate          | requetsed flow rate                    | double            | m/sec^3 |
         */
        struct CirculateState
        {
            DataTypes::Status status;

            // actuals
            double            actualFlowRate;
            double            actualStandpipePressure;

            // constraints
            double            minFlowRate;
            double            maxFlowRate;
            double            minStandpipePressure;
            double            maxStandpipePressure;

            // targets
            double            targetFlowRate;
        };
    };
};
