module plc
{
    module process
    {
        // QoSLibrary: EdgeBaseLibrary
        // QoSProfile: PlcProfile
        //@copy-c-declaration static const char PLC_HOIST_REQUEST_TOPIC[] = "HoistRequestTopic";

        /**
         * \brief requested state change in the hoisting system.
         *
         * \ingroup SafeHoistFunctions
         *
         * | Variable          | Description                                      | Data Type           | Unit  |
         * | ----------------- | -------------------------------------------------| --------------------| ------|
         * | targetVelocity    | requested target in m/s                          | double              | m/sec |
         * | targetPosition    | requested target position in m                   | double              | m/sec |
         */
        struct PlcHoistRequest
        {
            double              targetVelocity;
            double              targetPosition;
        };

        // QoSLibrary: EdgeBaseLibrary
        // QoSProfile: PlcProfile 
        //@copy-c-declaration static const char PLC_HOIST_STATE_TOPIC[] = "HoistStateTopic";

        /**
         * \brief current state of the hoisting system.
         *
         * \ingroup SafeHoistFunctions
         *
         * | Variable          | Description                            | Data Type         | Unit  |
         * | ----------------- | -------------------------------------- | ----------------- | ------|
         * | status            | status of hoisting system              | Datatypes::Status | N/A   |
         * | actualHookload    | actual system hookload                 | double            | N     |
         * | actualVelocity    | actual hoist velocity                  | double            | m/sec |
         * | actualPosition    | actual target position                 | double            | m     |
         * | maxHookload       | maximum hookload allowed by system     | double            | N     |
         * | maxHoistVelocity  | maximum hoist velocity                 | double            | m/sec     |
         * | maxLowerVelocity  | maximum lower velocity                 | double            | m/sec |
         * | maxHoistPosition  | maximum hoist position                 | double            | m     |
         * | maxLowerPosition  | maximum lower position                 | double            | m     |
         * | targetVelocity    | target hoist velocity                  | double            | m/sec |
         * | targetPosition    | target hoist position                  | double            | m     |
         */
        struct PlcHoistState
        {
            long    status;

            // actuals
            double  actualHookload;
            double  actualVelocity;
            double  actualPosition;

            // constraints
            double  maxHookload;
            double  maxHoistVelocity;
            double  maxLowerVelocity;
            double  maxHoistPosition;
            double  maxLowerPosition;

            // targets
            double  targetVelocity;
            double  targetPosition;
        };
    };
};
